spring.application.name=electromart

# ===============================
# SERVER
# ===============================
server.port=8080


# ===============================
# DATASOURCE (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/electromartdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# CORS
# ===============================
allowed.origin=http://localhost:5173


# ===============================
# JWT
# ===============================
jwt.secret=9b8f30c4d3e17a847f55ae0b32ac9e5017628b0df0293b442d6a7df42a893f28
jwt.expiration-ms=86400000



# shivamyogi122@gmail.com/Shivam@123456